### ISSUE TITLE
Replace CheckList by RadioButtons

### ISSUE THREAD

**Issue by Akronix** [Grasia/WikiChron-networks#20]
Since user should only select one wiki and one network, checklist should be replaced by Radiobuttons, at least for the network types, or make it single-item selectable otherwise.

**Comment by Akronix** [comment]
To do this with the wikis selector would require a lot of work (technically) that is not worthwhile.
Instead, I disable the GENERATE button when more than one wiki is selected.
That is good enough for now. Closing this.

**Comment by javiag** [comment]
It would be good to display something to inform the user there's a mistake in the selection.

This is low priority, of course.

**Comment by Akronix** [comment]
@javiag by "a mistake in the selection" you are referring to the case where the user has selected more than one wiki, right?

**Comment by javiag** [comment]
Yes!
