### ISSUE TITLE
[Network] Social

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/WikiChron-networks#30]
A new network where the content is about the wiki's discuss. It'd be like the talk network but it'd compute the associated namespaces.

Example of discuss forum: https://zelda.fandom.com/d/f
Fandom namespaces (ns. 110, 111): http://community.wikia.com/wiki/Help:Namespace

**Comment by Akronix** [comment]
Unfortunately, Fandom is not willing to make the data of the Discuss tool available, so this social dimension of wikis is not something that could be easily added to WikiChron.
We have decided that the [wiki-styled forums](https://community.wikia.com/wiki/Help:Wiki-style_forums) are too technical and not different enough from talk pages, so its interest is not as high.
