### ISSUE TITLE
Zelda.csv doesn't produce a network

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/WikiChron-networks#8]
The script clogs when you use zelda.csv to create a network

**Comment by FRYoussef** [comment]
It works, but it takes too much time, zelda.csv has 7739 users, and 64249 pages and the algorithm to create the network takes O(n^3) time

**Comment by Akronix** [comment]
Hum, interesting. Ideas on how to optimize or reduce time in order to be able to visualize big wikis?
