### ISSUE TITLE
Sidebar bugs cytoscape

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/WikiChron-networks#9]
When you hide the sidebar the cytoscape component gets bugged

**Comment by Akronix** [comment]
Do you mean the left side bar?

**Comment by Akronix** [comment]
@FRYoussef Could you, please, give me instructions to reproduce the issue and know exactly what the bugs are?

I've noticed that ***sometimes*** (I'm not sure if always), when I the sidebar gets hidden the cytoscape component throws these errors:
```TypeError: n is not a function```

Do you mean those?

**Comment by FRYoussef** [comment]
ok,
first, select a wiki to show, then the left side bar automatically hides, next, tap on the hide button in order to emerge the left side bar, and now, try to move any node from the network

**Comment by FRYoussef** [comment]
> 
> 
> ok,
> first, select a wiki to show, then the left side bar automatically hides, next, tap on the hide button in order to emerge the left side bar, and now, try to move any node from the network

Between the mouse click and the cytoscape click there is an offset equals to the left side bar width

**Comment by Akronix** [comment]
Closing this in favor of #22 for the specific bug about the sidebar offset. The other bugs seem to have been solved when we updated to dash-cytoscape 0.0.4
